org.gradle.jvmargs=-Xmx1G
minecraft_version=26.3
fabric_version=0.160.6+26.3
loader_version=0.19.5
kotlin_loader_version=1.13.13+kotlin.2.4.10
maven_group=com.github.noamm9
archives_base_name=DancingSquared
mod_version=1.2.9

noammaddons_type=cheat
# Last successful NoammAddons 26.3 CI build (1.2.9).
noammaddons_version=6d6c54301f252657739988a1247bece7a06abf4e
noammaddons_mod_version=1.2.9
